version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_bom
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
  backend:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/ai_bom
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      SECRET_KEY: changeme
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
  worker:
    build: .
    command: ["python", "-m", "ai_bom.main", "worker"]
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/ai_bom
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      SECRET_KEY: changeme
    depends_on:
      - backend
      - redis
volumes:
  minio-data:

