apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-bom-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-bom-backend
  template:
    metadata:
      labels:
        app: ai-bom-backend
    spec:
      containers:
        - name: backend
          image: your-org/ai-bom-backend:latest
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ai-bom-secrets
                  key: database_url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-bom-secrets
                  key: secret_key
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

