apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-bom-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-bom-worker
  template:
    metadata:
      labels:
        app: ai-bom-worker
    spec:
      containers:
        - name: worker
          image: your-org/ai-bom-backend:latest
          command: ["python", "-m", "ai_bom.main", "worker"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ai-bom-secrets
                  key: database_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ai-bom-secrets
                  key: redis_url
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

